/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)
    
    // OpenCSV dependency for parsing CSV files
    implementation("com.opencsv:opencsv:5.7.1")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "app.gpuslave.first.First"
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}

// run {
//     standardInput = System.in
// }

tasks.javadoc {
    options {
        memberLevel = JavadocMemberLevel.PRIVATE
    }
}
