name: Run Java

on:
  push:
    branches:
      - feature/add-java-runtime
  workflow_dispatch:


jobs:
  build:
    name: "Compile and Run Java"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'gradle'
      
      - name: Setup Gradle 
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build

      - name: Run
        run: ./gradlew run







      # - name: Compile
      #   run: javac src/main/java/app/gpuslave/first/First.java -d .

      # - name: Run
      #   run: java app.gpuslave.first.First