name: Run Java

on:
  push:
    branches:
      - feature/add-java-runtime
  workflow_dispatch:

jobs:
  build:
    name: "Compile and Run Java With Gradle"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK with Java-21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'gradle'
      
      - name: Setup Gradle 
        uses: gradle/actions/setup-gradle@v4
      
      - name: Setup Gradle Wrapper
        run: gradle wrapper

      - name: Build
        run: ./gradlew build

      - name: Run
        run: ./gradlew run
      
      - name: Test
        run: ./gradlew test

      - name: Generate Docs
        run: ./gradlew javadoc